### ISSUE TITLE
netCDF4 1.5 er inkompatibel

### ISSUE THREAD

**Issue by pnsaevik** [bjornaa/ladim#2]
Hei Bjørn,

Den nye netCDF4 gir problemer.

For å teste, prøv følgende:

`np.array(netCDF4.num2date(0, 'seconds since 1970-01-01'), dtype=np.datetime64)`

Dette funker i netCDF4 1.4, men ikke i netCDF 1.5

Og det gjør at Forcing-klassen krasjer.

**Comment by pnsaevik** [comment]
Rettelse: Det er cftime 1.1 som er problemet, siden netCDF4-biblioteket bruker cftime direkte. Men problemet er uansett det samme.

**Comment by bjornaa** [comment]
Hei,


Jeg fikk samme problem, men trodde det kom fordi jeg jobber med ladim2.

Men, det kommer i standard ladim også.


Jeg legger inn en fix:


   all_frames = np.array(all_frames, dtype=np.datetime64)
erstattes med:
    all_frames = np.array([np.datetime64(tf) for tf in all_frames])

Det fungerer (og vil nok og virke med gammel netcdf)

På master github om få minutter.

Bjørn



________________________________
Fra: Pål Næverlid Sævik <notifications@github.com>
Sendt: torsdag 2. april 2020 14.03
Til: bjornaa/ladim
Kopi: Subscribed
Emne: [bjornaa/ladim] netCDF4 1.5 er inkompatibel (#2)


Hei Bjørn,

Den nye netCDF4 gir problemer.

For å teste, prøv følgende:

np.array(netCDF4.num2date(0, 'seconds since 1970-01-01'), dtype=np.datetime64)

Dette funker i netCDF4 1.4, men ikke i netCDF 1.5

Og det gjør at Forcing-klassen krasjer.
